# Generated by Django 2.2 on 2020-03-15 22:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200315_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_test',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
