# Generated by Django 2.2 on 2020-03-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20200315_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(null=True, upload_to='postsimages'),
        ),
    ]
